### ISSUE TITLE
Hello, can I ask for the code of CUB training MLDG model? The MLDG model does not have code for CUB in Learning to Generalize: Meta-Learning for Domain Generalization, thank you.

### ISSUE THREAD

**Issue by liuyiming199721** [PRIS-CV/On-the-fly-Category-Discovery#3]
Hello, can I ask for the code of CUB training MLDG model? The MLDG model does not have code for CUB in Learning to Generalize: Meta-Learning for Domain Generalization, thank you.

**Comment by RuoyiDu** [comment]
> Hello, can I ask for the code of CUB training MLDG model? The MLDG model does not have code for CUB in Learning to Generalize: Meta-Learning for Domain Generalization, thank you.

Hi, thank you for your interest. We have not organized this part of the code. But you can easily implement it based on our baseline code and learn2learn library (https://github.com/learnables/learn2learn). Just wrap the model by 
`maml = l2l.algorithms.MAML(model, lr)`
and then follow the pipeline of MLDG.
